build:
	go build -o gosst-http cmd/gosst-http/gosst-http.go
	go build -o gosst-tcp cmd/gosst-tcp/gosst-tcp.go
	go build -o gosst-file cmd/gosst-file/gosst-file.go

clean:
	go clean
	rm gosst-http
	rm gosst-tcp
	rm gosst-file
