"""Add synchronizable base

Revision ID: 1ecf18307d08
Revises: 7f09aaaf3dbc
Create Date: 2024-01-31 14:12:21.758985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ecf18307d08'
down_revision = '7f09aaaf3dbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated', sa.Integer(), server_default=sa.text('(unixepoch())'), nullable=False))
        batch_op.add_column(sa.Column('client_updated', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('deleted', sa.Integer(), nullable=True))

    with op.batch_alter_table('calibration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated', sa.Integer(), server_default=sa.text('(unixepoch())'), nullable=False))
        batch_op.add_column(sa.Column('client_updated', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('deleted', sa.Integer(), nullable=True))

    with op.batch_alter_table('calibration_method', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated', sa.Integer(), server_default=sa.text('(unixepoch())'), nullable=False))
        batch_op.add_column(sa.Column('client_updated', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('deleted', sa.Integer(), nullable=True))

    with op.batch_alter_table('linkage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated', sa.Integer(), server_default=sa.text('(unixepoch())'), nullable=False))
        batch_op.add_column(sa.Column('client_updated', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('deleted', sa.Integer(), nullable=True))

    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated', sa.Integer(), server_default=sa.text('(unixepoch())'), nullable=False))
        batch_op.add_column(sa.Column('client_updated', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('deleted', sa.Integer(), nullable=True))

    with op.batch_alter_table('setup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated', sa.Integer(), server_default=sa.text('(unixepoch())'), nullable=False))
        batch_op.add_column(sa.Column('client_updated', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('deleted', sa.Integer(), nullable=True))

    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated', sa.Integer(), server_default=sa.text('(unixepoch())'), nullable=False))
        batch_op.add_column(sa.Column('client_updated', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('deleted', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.drop_column('deleted')
        batch_op.drop_column('client_updated')
        batch_op.drop_column('updated')

    with op.batch_alter_table('setup', schema=None) as batch_op:
        batch_op.drop_column('deleted')
        batch_op.drop_column('client_updated')
        batch_op.drop_column('updated')

    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_column('deleted')
        batch_op.drop_column('client_updated')
        batch_op.drop_column('updated')

    with op.batch_alter_table('linkage', schema=None) as batch_op:
        batch_op.drop_column('deleted')
        batch_op.drop_column('client_updated')
        batch_op.drop_column('updated')

    with op.batch_alter_table('calibration', schema=None) as batch_op:
        batch_op.drop_column('deleted')
        batch_op.drop_column('client_updated')
        batch_op.drop_column('updated')

    with op.batch_alter_table('calibration_method', schema=None) as batch_op:
        batch_op.drop_column('deleted')
        batch_op.drop_column('client_updated')
        batch_op.drop_column('updated')

    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.drop_column('deleted')
        batch_op.drop_column('client_updated')
        batch_op.drop_column('updated')

    # ### end Alembic commands ###
