"""Make session.data nullable

Revision ID: 5c40381ea62d
Revises: 8e4c33e09ccd
Create Date: 2024-05-15 19:59:27.811755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c40381ea62d'
down_revision = '8e4c33e09ccd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=sa.BLOB(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=sa.BLOB(),
               nullable=False)

    # ### end Alembic commands ###
