"""Add suspension properties to session

Revision ID: 8e4c33e09ccd
Revises: ef9b3861a756
Create Date: 2024-05-02 17:46:55.543827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e4c33e09ccd'
down_revision = 'ef9b3861a756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('front_springrate', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('rear_springrate', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('front_hsc', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rear_hsc', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('front_lsc', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rear_lsc', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('front_lsr', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rear_lsr', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('front_hsr', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rear_hsr', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_column('rear_hsr')
        batch_op.drop_column('front_hsr')
        batch_op.drop_column('rear_lsr')
        batch_op.drop_column('front_lsr')
        batch_op.drop_column('rear_lsc')
        batch_op.drop_column('front_lsc')
        batch_op.drop_column('rear_hsc')
        batch_op.drop_column('front_hsc')
        batch_op.drop_column('rear_springrate')
        batch_op.drop_column('front_springrate')

    # ### end Alembic commands ###
