"""Initial migration

Revision ID: ea6262808b9d
Revises: 
Create Date: 2023-12-01 18:34:48.153926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea6262808b9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calibration_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('data', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('linkage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('head_angle', sa.Float(), nullable=False),
    sa.Column('front_stroke', sa.Float(), nullable=False),
    sa.Column('rear_stroke', sa.Float(), nullable=False),
    sa.Column('raw_lr_data', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('track',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('hash', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('calibration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('method_id', sa.Integer(), nullable=False),
    sa.Column('inputs', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['method_id'], ['calibration_method.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('setup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('linkage_id', sa.Integer(), nullable=False),
    sa.Column('front_calibration_id', sa.Integer(), nullable=True),
    sa.Column('rear_calibration_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['front_calibration_id'], ['calibration.id'], ),
    sa.ForeignKeyConstraint(['linkage_id'], ['linkage.id'], ),
    sa.ForeignKeyConstraint(['rear_calibration_id'], ['calibration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('board',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('setup_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['setup_id'], ['setup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('setup_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['setup_id'], ['setup.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_html',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('script', sa.String(), nullable=False),
    sa.Column('travel', sa.String(), nullable=False),
    sa.Column('velocity', sa.String(), nullable=False),
    sa.Column('map', sa.String(), nullable=False),
    sa.Column('lr', sa.String(), nullable=False),
    sa.Column('sw', sa.String(), nullable=False),
    sa.Column('f_thist', sa.String(), nullable=True),
    sa.Column('f_fft', sa.String(), nullable=True),
    sa.Column('f_vhist', sa.String(), nullable=True),
    sa.Column('r_thist', sa.String(), nullable=True),
    sa.Column('r_fft', sa.String(), nullable=True),
    sa.Column('r_vhist', sa.String(), nullable=True),
    sa.Column('cbalance', sa.String(), nullable=True),
    sa.Column('rbalance', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_html')
    op.drop_table('session')
    op.drop_table('board')
    op.drop_table('setup')
    op.drop_table('calibration')
    op.drop_table('user')
    op.drop_table('track')
    op.drop_table('linkage')
    op.drop_table('calibration_method')
    # ### end Alembic commands ###
